## Stub to invoke targets of ../Makefile

.PHONY : joos0 all joos0.native joos0.byte joos0.top joos0.debug joos0.profile

joos0:
	cd ..; $(MAKE) joos0
all:
	cd ..; $(MAKE) all
joos0.native:
	cd ..; $(MAKE) joos0.native
joos0.byte:
	cd ..; $(MAKE) joos0.byte
joos0.top:
	cd ..; $(MAKE) joos0.top
joos0.debug:
	cd ..; $(MAKE) joos0.debug
joos0.profile:
	cd ..; $(MAKE) joos0.profile
clean:
	cd ..; $(MAKE) clean
htdoc:
	cd ..; $(MAKE) htdoc
